### ISSUE TITLE
Create list of required input parameters

### ISSUE THREAD

**Issue by MichielTukker** [Nieuwe-Warmte-Nu/simulator-core#1]
Create list of required input parameters not provided in the ESDL

**Comment by octavianor** [comment]
i am starting the document in this link https://365tno.sharepoint.com/:x:/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/[asset_parameter.xlsx](https://365tno.sharepoint.com/:x:/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/asset_parameter.xlsx?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=fcZek8)?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=fcZek8

**Comment by octavianor** [comment]
the list is done
