### ISSUE TITLE
Create basic production class

### ISSUE THREAD

**Issue by samvanderzwan** [Nieuwe-Warmte-Nu/simulator-core#14]

**Comment by vanmeerkerk** [comment]
Two possible methods of operation:

1. Deliver a specified amount of heat at a fixed temperature. Mass flow is a dependent property.
2. Deliver pressure to the system at a fixed temperature. Mass flow is fixed by the remainder of the system.

**Comment by vanmeerkerk** [comment]
in_service results in an action that is similar to the "disuse" functionality of WANDA. In the results the corresponding pipe has only NaN values.
