### ISSUE TITLE
Create list of output data and their structure

### ISSUE THREAD

**Issue by MichielTukker** [Nieuwe-Warmte-Nu/simulator-core#2]
Create list of output data and their structure

**Comment by octavianor** [comment]
i am starting the document in this link ([https://365tno.sharepoint.com/❌/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/asset_parameter.xlsx?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=CjOqWv](https://365tno.sharepoint.com/:x:/r/teams/P060.55186/TeamDocuments/Team/Work/Backend/Simulator/asset_parameter.xlsx?d=wafd9b7c395a84a6c8f231924eedf4897&csf=1&web=1&e=CjOqWv))

**Comment by octavianor** [comment]
the list is done
